### ISSUE TITLE
submit_local_code.jobscript has errors that can cause issues on the grid 

### ISSUE THREAD

**Issue by calcuttj** [DUNE/dune-prod-utils#5]
https://github.com/DUNE/dune-prod-utils/blob/main/justIN-examples/submit_local_code.jobscript#L44-L48

This is the incorrect procedure for this type of workflow. sourcing local products is only intended for interactive work. The correct procedure is instead to 

1. export PRODUCTS=\<input_dir\>:$PRODUCTS
2. setup \<product\>

Note, one should never mix sourcing local products & mrbslp with ups setup of a product in the local products. Especially not on the grid.

**Comment by ahiguera-mx** [comment]
@calcuttj 
Thanks for reporting this, I have pushed a [fix](https://github.com/DUNE/dune-prod-utils/commit/c5a3c303320ad8ddd7c55e4fe3804fa85d21c26c), let me know if you find additional issues
