### ISSUE TITLE
meta data creation script needs to add both scope and name to the dune.dataset_name

### ISSUE THREAD

**Issue by dougbenjamin** [DUNE/dune-prod-utils#6]
Currently the metadata files in the area -

/pnfs/dune/persistent/dunepro/caf_fd_2024/*

need to be modified so that

The metadata value "dune.dataset_name":"<scope>:<dataset name>"

Currently for example - 

_"dune.dataset_name": "merged_fardet-vd_root-tuple_v09_91_02d01_cafmaker_dunevd10kt_1x8x6_3view_30deg_runreco-nuenergy_geov3_prodgenie_nu_dunevd10kt_1x8x6_3view_30deg_physics"_

should be
_"dune.dataset_name": "fardet-vd:merged_fardet-vd_root tuple_v09_91_02d01_cafmaker_dunevd10kt_1x8x6_3view_30deg_runreco-nuenergy_geov3_prodgenie_nu_dunevd10kt_1x8x6_3view_30deg_physics_"

**Comment by ahiguera-mx** [comment]
Thanks @dougbenjamin this has been fixed in the https://github.com/DUNE/data-mgmt-ops/pull/754
